# Studiedesign

## Introduksjon

Mennesker i vesten lever lenger og lenger, og eldrebølgen er et faktum. På bakgrunn av dette er det derfor et stort behov for å finne ut hvordan eldre mennesker kan bevare helsen best mulig. I denne rapporten skal jeg se på fem studier som har sett på styrketrening som en metode for å bedre helsen til eldre mennesker [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. Alle fem studiene ønsker å finne ut hvordan man kan legge opp styrketrening som gir god effekt på helsen (mentalt og fysisk) og dermed gjøre det lettere å gi gode treningsanbefalinger. En oppsummering av studiene er vist i tabell 1.

I fire av studiene ble det sett på forskjellige måter man rent praktisk bør gjennomføre styrketrening [@schott2019 ; @turpela2017; @vikberg2019; @vincent2002]. I @schott2019 ble det for eksempel sett på effekten av å trene med styrketreningsapparater mot frivektstrening [@schott2019]. Studien til @geirsdottir2012 skiller seg fra de andre da den hovedsakelig så på den generelle effekten av trening [@geirsdottir2012]. Den så som de andre på styrke- og muskeladaptasjoner, men inkluderte et spørreskjema om hvordan treningen påvirket livskvaliteten [@geirsdottir2012].

På bakgrunn av studiespørsmålene og svarene de vil gi oss, vil studiene gi en styrke til den allerede etablerte anbefalingen om at eldre bør trene styrke for å opprettholde eller bedre helsen [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019 @vincent2002]. I tillegg vil studiene gjøre det lettere å gi gode anbefalinger da de løser noen praktiske spørsmål rundt selve gjennomføringen av styrketrening [@geirsdottir2012 ; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. @vikberg2019 foreslår at en enkel form for styrketrening som man kan gjøre hjemme er nok for å styrke muskulatur og bedre helsen. Dette vil gjøre styrketreningseffekten oppnåelig for alle, og ikke bare de som trener på treningssenter [@vikberg2019].

## Diskusjon av metode

Fire av studiene var av studietypen Randomisert kontrollert undersøkelse (RCT) hvor det var en, to eller tre intervensjonsgrupper og en kontrollgruppe [@schott2019; @turpela2017; @vikberg2019; @vincent2002]. Hvem som var i hvilke grupper, ble randomisert tilfeldig. Antallet i gruppene var nesten likt fordelt i intervensjon og kontroll med unntak av @vincent2002. «Nesten likt» vil si at det stort sett var flere i de gruppene det krevde mest av (treningsgruppene). Samtidig var dette gruppene med flest frafall, sånn at det ved studieslutt nesten var utlignet [@schott2019; @turpela2017; @vikberg2019]. I @vincent2002 var det større forskjell på kontroll og intervensjon (16 i kontroll, 24 og 22 i intervensjon) uten at det blir opplyst noen grunn til det. Å ha en blokkrandomisering som de tre andre nevnt over, ville gitt studien et styrket design. Når det er forskjellige størrelser vil det bli vanskeligere å sammenligne, da mindre grupper gir bredere konfidensintervall og lavere statisk styrke [@hulley2013, s. 63, 146].

Da dette er studier som ser på trening er «blinding» vanskelig, dermed nevnte studiene heller ikke noe om dette [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. For å unngå forskingsfusk er det likevel gunstig at testpersonell ikke vet hvem som er i hvilken gruppe, da testpersonell skal gjennomføre alle tester like godt, selv om man ofte ønsker et resultat i favør hypotesen [@hulley2013, s. 148-149].

@geirsdottir2012 var en klinisk studie uten kontrollgruppe, de hadde altså en stor gruppe (265 kvinner og menn) som trente samme styrketreningsprogrammet. At de ikke hadde en kontrollgruppe innrømmet studiegruppen selv at var en svakhet [@geirsdottir2012]. Samtidig argumenterer de for at eldre mennesker ikke kan forvente en økning i styrke, muskelmasse og muskelfunksjon uten å trene [@geirsdottir2012] . På bakgrunn av dette mente de at det var nok å sammenligne med testresultat ved start [@geirsdottir2012]. Det er mulig å forstå argumentasjonen til @geirsdottir2012 når de i tillegg har såpass mange deltagere som de har. Samtidig hadde en definert kontrollgruppe og et RCT-design gjort studien sterkere som en studie som ønsker å finne ut av noe [@hulley2013, s. 87]. Studien vil gå under studiekategorien Case-serie som er mer egnet til å se på karakteristika, og i denne sammenhengen av styrketrening på eldre [@hulley2013, s. 87]. Dette kommer frem da resultatet av spørreskjema om livskvalitet var noe av det viktigste, men burde kommet bedre frem når de diskuterer de andre variablene [@geirsdottir2012].

Populasjonen som er ønsket å treffe er relativt friske eldre kvinner og menn[@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. Ingen av studiene har en eksplisitt definisjon av «eldre», men totalt i studiene var det et aldersspenn på 60-92 år, og gjennomsnittsalderen i de forskjellige studiene var rundt 70 år (flest rett under) [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. Den eldre befolkningen er en svært heterogen gruppe, noe som gjør det vanskelig med ekskluderingskriterier. Studiene godtok da det som ble definert som milde sykdommer som ikke påvirker treningen [@geirsdottir2012; @schott2019; @turpela2017; @vincent2002]. Unntaket er til en viss grad @vikberg2019 hvor det det eneste eksklusjonskriteriet var sarkopeni. Samtidig kan det tyde på at det var relativt god helse blant deltagerene da de alle var 70 år, ikke hadde sarkopeni og klarete å gjennomføre treningen [@vikberg2019]. Totalt sett treffer studiene godt på populasjonen da alle har et høyt antall deltagere og har kvalifikasjonskriterier som gjør det mulig for «vanlig» eldre folk å være med [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002].

Rekruteringen av deltagere ble gjort ved hjelp av brev og annonser med unntak av @schott2019 [@geirsdottir2012; @turpela2017; @vikberg2019; @vincent2002]. Han hentet deltagere fra en treningsgruppe som var etablert på studiestedet [@schott2019]. Felles for alle studiene var at det va en frivillig deltagelse [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. @schott2019 og @vincent2002 uttrykte et krav om at det måtte være statistisk styrke på 80%. @schott2019 gjorde også et estimat hvor de så at det var behov for 26 deltagere for å se en signifikant forskjell ved signifikantgrense på 5% når de godtok en sannsynlighet på 80% (de inkluderte 32 personer). De andre studiene nevnte ikke noe om statistisk styrke, og kunne med fordel vist til en estimering av deltagere som krevdes for en gitt statistisk styrke. @turpela2017 innrømmet at det kunne bli vanskelig å se forskjell mellom gruppene da utrente ofte får god effekt uansett. Dette problemet kunne blitt kontrollert for om man hadde gjort en powerbergening og inkludert tilstrekkelig deltagere [@hulley2013, s. 48-49] .

Alle fem studiene hadde pre-post-design hvor Scott et al. også i tillegg hadde tester i uke 10, uke 26 og 6 uker etter post-testen i uke 26 [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. I alle studiene ble det gjort idrettsfysiologiskse tester av styrke, men også funksjonelle tester som hadde som mål å se hvordan styrken kom til uttrykk i dagligdagse gjøremål (gå test, gripe test osv.) [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. @geirsdottir2012 la som nevnt også en del vekt på spørreskjema som ble gitt før og etter intervensjon. @schott2019 hadde også et spørreskjema, men dette ble bare gitt etter og var en evaluering av treningen. Treningen som ble gjennomført av intervensjonsgruppene ble gjort på treningssenter eller treningslokale på studiestedet [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. I studien til @vincent2002 sendte deltagerne inn treningsdagbøker for hver økt som det så det ble gitt tilbakemeldinger på. I de fire andre studiene var det kvalifiserte trenere som veiledet deltagerne igjennom øktene [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019]. Kontrollgruppen ble instruert i å leve som vanlig og ikke trene [@schott2019; @turpela2017; @vikberg2019; @vincent2002]. Treningsperiodene var fra 10 uker til 26 uker [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002].

Studiene hadde som nevnt som mål å finne ut hvordan eldre bør trene og hvilke effekter det er av styrketrening [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. For å finne ut dette ble det sett på forskjellige variabler for styrke, kroppssammensetning (spesielt fettfri masse), muskelstørrelse, men også variabler som skulle reflektere dagligdagse gjøremål [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. @vincent2002 la for eksempel en del vekt på en trappetest hvor deltagerne skulle gå en trapp så fort som mulig. Dette er viktig da noe av hovedgrunnen for å trene styrke for eldre nettopp er å mestre dagligdagse gjøre mål [@vincent2002].

I analysen av studiene var det ønskelig å finne forskjeller i resultat mellom grupper, her ble det brukt forskjellige statistiske tester. I tre av studiene hvor det var en eller to grupper ble brukt paret t-test får så se forskjell innad i gruppene [@geirsdottir2012; @vikberg2019; @schott2019]. @vincent2002 brukte 3x2 ANOVA for å se forskjell innad og mellom gruppene og så etter en interaksjon mellom gruppe og tid. @vincent2002 fant ikke foradring mellom gruppene på pretest, men gjorde likevel en ANCOVA for å kontrollere for forskjeller ved pre-test når de analyserte forandringen mellom gruppene. To av de andre studier gjorde også ANCOVA for å se forandring mellom gruppene og effekten av tid ved gjentatte målinger [@schott2019; @vikberg2019]. @turpela2017 brukte her en-veis-ANOVA for å kontrollere for ulikheter ved pre-test. Denne kontrollen for pre-verider gir styrke til resultatet i studiene da den kontrollerer for eventuelle forskejller i gruppene ved pre-test. For @geirsdottir2012 er ikke denne analysemetoden mulig da det bare er en gruppe. @schott2019 brukte også MANCOVA for å gjøre statistikk på variablene som ble mål flere enn to ganger og på spørreskjammaet han brukte. @geirsdottir2012 brukte Wilconxon's test for analyse av spørreskjemaet sitt. Tre av studiene brukte også post hoc tester som vil gi et mer troverdig resultat da den kontrollerer resultatet for falsk positiv (type I feil) [@hulley2013, s. 50-52][@schott2019; @turpela2017; @vincent2002]. Alle hadde signifikantgrense ved P = 5% med unntak av en ANCOVA-test @vikberg2019 gjorde som gjorde en interaksjon mellom kjønn og intervensjon, hvor P = 10% [@geirsdottir2012; @schott2019; @turpela2017; @vincent2002]. Denne interaksjonen til @vikberg2019 vil med dette lettere godta at det er en forskjell mellom kjønnene.

## Resultat og anbefaling

I tre av studiene som sammenlignet intervensjon mot kontroll, ble det ikke sett forskjell på muskelmasse, men @vikberg2019 fant forskjell i muskelmasse [@schott2019; @turpela2017; @vincent2002]. @vikberg2019 fant ikke forskjell i styrke fra kontrollgruppen, men de gjorde de tre andre [@schott2019; @turpela2017; @vincent2002]. På funksjonell styrke ga alle studiene positiv effekt på funksjonelle tester [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. I de studiene som sammenlignet flere treningsprotokoller var det liten forskjell mellom det forskjellige treningsprotokollene, men alle skilte seg fra kontrollgruppen [@schott2019; @turpela2017; @vikberg2019; @vincent2002]. @geirsdottir2012 fant en liten forbedring av livskvalitet. Alt i alt greide de delvis å gi et positivt svar på hypotesen [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002].

Alle studiene konkluderte med at styrketrening fungerte [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. For å oppsummere anbefalingene, er det nok å trene styrke 1-2 ganger i uken, så lenge det er helkroppsøkt [@turpela2017; @vikberg2019]. En ytterlig effekt vil man få om man trener med frivekter, spesielt på ben og triceps, som er viktige muskelgrupper for eldre [@schott2019]. Det er også nok å gjøre 13 rep på 50% 1RM [@vincent2002]. Antall serier er ikke sett på, men basert på studiene burde 1-2 være nok [@geirsdottir2012; @schott2019; @turpela2017]. Det kommer også fram at all trening som ble sett på gav en effekt [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. Treningen vil vedlikeholde muskelmassen din, øke styrken din, gjøre praktiske gjøremål lettere og det vil kunne øke livskvaliteten din [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002]. Denne konklusjonen og anbefalingen gjelder for relativet friske eldre mennesker som ikke er vant til å trene og som har en lav muskelmasse, dog ikke kritisk lav [@geirsdottir2012; @schott2019; @turpela2017; @vikberg2019; @vincent2002].

## Videre forskning

Det er enda ikke veldig tydelig hvilke treningsprogram som gir god effekt på bedret funksjonsevne [@turpela2017]. @schott2019 foreslår at studeier med frivekter kan være løsningen. I tillegg burde man gjøre studier hvor man kontrollerer proteininntaket hos eldre da dette kan være så lavt at det påvirker styrkefremgangen [@turpela2017].

```{r tesksttabell, echo=FALSE, message=FALSE, warning=FALSE, tab.cap = "Tabellen viser en oppsummering av studiene"}
library(readxl)
library(flextable)
tabelltekst <- read_excel("data/teksttabell.xlsx")

tabelltekst%>%
flextable()
```
